## gateway-rs default configuration file
##
## NOTE: Do _NOT_ change values in this file. 
##   Override settings in settings.toml by putting the sections and
##   settings that need to be changed there.  

## Keypair is a string that supports specifying different locations for 
## the secrets. The default one is file based one since all devices 
## can support it.
##
## Override the setting by putting a keypair line in the 
## local settings.toml. Changing things in this file will be overwritten
## by upgrades. 
##
## File: 
keypair = "/etc/helium_gateway/gateway_key.bin"
## ECC608 based
# keypair = "ecc://i2c-1:96?slot=0"
# onboarding = "ecc://i2c-1:96?slot=15"
listen = "127.0.0.1:1680"
api = 4467
region = "US915"

[log]
method = "stdio"
level = "info"
timestamp = false

[cache]
max_packets = 20

[poc]
entropy_uri = "https://entropy.helium.io/entropy"
ingest_uri = "http://mainnet-pociot.helium.io:9080"

[config]
pubkey = "115PmCR6fpFihdjw626JXYdUEdzwjh66yoWzWkMvB9CRGEx1U6G"
uri = "http://3.132.190.192:8080"

