on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

name: ci

jobs:
  hygiene:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install protoc
        run: sudo apt-get install -y protobuf-compiler

      - name: cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: install dependencies
        run: sudo apt-get install -y libtss2-dev

      - name: check formatting
        run: |
          cargo fmt  -- --check

      - name: clippy
        run: |
          cargo clippy --all-features -- -D clippy::all

      - name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - arm-unknown-linux-gnueabihf
          - armv5te-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl
          - mips-unknown-linux-musl
          - mipsel-unknown-linux-musl
          - x86_64-tpm-debian-gnu

    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: davidB/rust-cargo-make@v1
      - uses: actions/checkout@v3

      - name: install cross
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        env:
          ## Allow cross install into PATH
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo: rust-embedded/cross

      - name: build target
        run: cargo make --profile ${{ matrix.target }} build

      - name: package target
        run: cargo make --profile ${{ matrix.target }} pkg

      - name: cache artifact
        uses: actions/upload-artifact@v3
        with:
          name: helium-gateway-${{ matrix.target }}
          if-no-files-found: error
          path: helium-gateway-*.tar.gz

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: [hygiene, build]
    runs-on: ubuntu-22.04

    steps:
      - name: fetch cached binaries
        uses: actions/download-artifact@v3
        with:
          path: helium-gateway-*.tar.gz

      - name: create release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          fail_on_unmatched_files: true
          files: helium-gateway-*.tar.gz
          name: ${{github.ref_name}}

  docker_buildx:
    # Ensure we don't publish images until we pass clippy.
    needs: [build]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Quay.io
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_MINER_USER }}
          password: ${{ secrets.QUAY_MINER_UPLOAD_TOKEN }}

      - name: Derive appropriate image-tag
        if: github.event_name == 'pull_request'
        run: echo "image_tag=PR${{ github.event.pull_request.number }}-$(git rev-parse --short ${{ github.event.pull_request.head.sha }})" >> $GITHUB_ENV

      - name: Derive appropriate image-tag
        if: github.event_name != 'pull_request'
        run: echo "image_tag=$(git describe)" >> $GITHUB_ENV

      # We publish all builds to the test-images repo.
      - name: Publish image to test-images repo
        run: |
          docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag quay.io/team-helium/test-images:gateway-"${{ env.image_tag }}" \
          --push \
          .

      # Publish to miner quay-repo on release only.
      - name: Publish release image to miner repo
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag quay.io/team-helium/miner:gateway-"${GITHUB_REF#refs/*/}" \
          --tag quay.io/team-helium/miner:gateway-latest \
          --push \
          .
